server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:/config/stats-server/
            - classpath:/config/gateway-server/
            - classpath:/config/user-service/
            - classpath:/config/event-service/
            - classpath:/config/request-service/
            - classpath:/config/moderation-service/
            - classpath:/config/aggregator/
            - classpath:/config/analyzer/
            - classpath:/config/collector/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
