services:
  discovery-server:
    build: ./infra/discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network

  config-server:
    build: ./infra/config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network

  stats-server:
    build: ./stats/stats-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      stats-db:
        condition: service_started
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-network

  user-service:
    build: ./core/user-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
      user-db:
        condition: service_started
    networks:
      - ewm-network

  event-service:
    build: ./core/event-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
      event-db:
        condition: service_started
    networks:
      - ewm-network

  request-service:
    build: ./core/request-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
      request-db:
        condition: service_started
    networks:
      - ewm-network

  moderation-service:
    build: ./core/moderation-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
      moderation-db:
        condition: service_started
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    networks:
      - ewm-network

  gateway-server:
    build: ./infra/gateway-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    networks:
      - ewm-network

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - ewm-network

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - ewm-network

  user-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - ewm-network

  event-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - ewm-network

  request-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: requests
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - ewm-network

  moderation-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: moderation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge
