CREATE TABLE IF NOT EXISTS moderation_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    admin_id BIGINT,
    comment_text TEXT NOT NULL,
    created_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_moderation_comments PRIMARY KEY (id)
);
