spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: user-service-internal
          uri: lb://user-service
          predicates:
            - Path=/internal/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**,/users/{userId}/events/{eventId}/requests/**
        - id: moderation-service
          uri: lb://moderation-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/moderation-comments
        - id: event-service-private
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/**
        - id: event-service-admin
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/admin/compilations/**,/admin/events/**
        - id: event-service-public
          uri: lb://event-service
          predicates:
            - Path=/events/**,/categories/**,/compilations/**

  config:
    import: "optional:configserver:"
    cloud:
      config:
        discovery:
          enabled: true
          service-id: config-server
        fail-fast: true
        retry:
          max-attempts: 15
          initial-interval: 2000
          multiplier: 1.5
          max-interval: 10000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}