spring:
  datasource:
    url: jdbc:postgresql://event-db:5432/events
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

event:
  moderation:
    page-size: 10
    default-from: 0

eureka:
  client:
    registry-fetch-interval-seconds: 5

grpc:
  client:
    collector:
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer:
      address: discovery:///analyzer
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
